#!/bin/bash
#SBATCH -p gpu
#SBATCH -t 10:00:00
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate pytorch11
python train.py --model_name=alexnet --root_path=/lustre2/0/wsdarts/ --dataset_name=imagenet --train_dataset_depth=3 --val_dataset_depth=3 --torchvision_dataset --pretrained_imagenet
source deactivate