#!/bin/bash
#SBATCH -p gpu
#SBATCH -t 100:00:00
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate pytorch11
python train.py --run_all_models --model_name=googlenet --root_path=/lustre2/0/wsdarts/ --dataset_name=fmnist --train_dataset_depth=1 --val_dataset_depth=1 --torchvision_dataset
source deactivate