#!/bin/bash
#SBATCH -p gpu
#SBATCH -t 100:00:00
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate pytorch11
python train.py --run_all_models --root_path=/lustre2/0/wsdarts/ --dataset_name=vggface2 --train_csv_path=/nfs/home4/mhouben/facenet_pytorch/datasets/train_vggface2.csv --val_csv_path=/nfs/home4/mhouben/facenet_pytorch/datasets/test_vggface2.csv --train_dataset_depth=3 --val_dataset_depth=3 --pretrained_imagenet
source deactivate