#!/bin/bash
#SBATCH -p gpu
#SBATCH -t 100:00:00
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate pytorch11
python train.py --run_all_models --root_path=/lustre2/0/wsdarts/ --dataset_name=inat_reptiles --train_csv_path=/nfs/home4/mhouben/facenet_pytorch/datasets/inaturalist2019_alphabet_csvs/train/Reptiles.csv --val_csv_path=/nfs/home4/mhouben/facenet_pytorch/datasets/inaturalist2019_alphabet_csvs/val/Reptiles.csv --train_dataset_depth=3 --val_dataset_depth=3 --pretrained_imagenet
source deactivate