#!/bin/bash
#SBATCH -p gpu
#SBATCH -t 15:00:00
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate pytorch11
python train.py --root_path=/lustre2/0/wsdarts/ --dataset_name=mnist --train_csv_path=/nfs/home4/mhouben/facenet_pytorch/datasets/omniglot_train_1_folder.csv --val_csv_path=/nfs/home4/mhouben/facenet_pytorch/datasets/omniglot_val_1_folder.csv --train_dataset_depth=1 --val_dataset_depth=1 --torchvision_dataset
source deactivate